export const COLLECTIBLE_STATUS = {
  ACTIVE: "ACTIVE",
  ON_HOLD: "ON_HOLD",
  SOLD: "SOLD",
} as const;
export type COLLECTIBLE_STATUS =
  (typeof COLLECTIBLE_STATUS)[keyof typeof COLLECTIBLE_STATUS];
export const TRANSACTION_STATUS = {
  TRANSACTION_UNCONFIRMED: "TRANSACTION_UNCONFIRMED",
  TRANSACION_CONFIRMED: "TRANSACION_CONFIRMED",
  TRANSACTION_FAILED: "TRANSACTION_FAILED",
} as const;
export type TRANSACTION_STATUS =
  (typeof TRANSACTION_STATUS)[keyof typeof TRANSACTION_STATUS];
