/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as syntethicNftSol from "./SyntethicNFT.sol";
export { MPMNFT__factory } from "./MPMNFT__factory";
export { MarketplaceContract__factory } from "./MarketplaceContract__factory";
export { MarketplaceWithPhase__factory } from "./MarketplaceWithPhase__factory";
