/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IWhitelistVerifier,
  IWhitelistVerifierInterface,
} from "../../../../../../src/blockchain/evm/contracts/interfaces/IWhitelistVerifier";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
      {
        internalType: "bytes32",
        name: "merkleRoot",
        type: "bytes32",
      },
      {
        internalType: "bytes32[]",
        name: "merkleProof",
        type: "bytes32[]",
      },
    ],
    name: "verifyWhitelist",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
] as const;

export class IWhitelistVerifier__factory {
  static readonly abi = _abi;
  static createInterface(): IWhitelistVerifierInterface {
    return new Interface(_abi) as IWhitelistVerifierInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IWhitelistVerifier {
    return new Contract(address, _abi, runner) as unknown as IWhitelistVerifier;
  }
}
